language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - composer update --prefer-dist
script:
  - vendor/bin/phpunit
after_script:
  - vendor/bin/test-reporter --coverage-report="test/coverage/clover.xml"

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/155f53c8074ea0a9073e
    on_success: always
    on_failure: always
    on_start: never
