language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
  - nightly

matrix:
  allow_failures:
    - php: nightly
  fast_finish: true

before_script:
  - composer update --prefer-dist
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  
script:
  - vendor/bin/phpunit

after_script:
  - ./cc-test-reporter format-coverage test/coverage/clover.xml --input-type clover
  - ./cc-test-reporter upload-coverage

cache:
  directories:
    - $HOME/.composer/cache/files

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/155f53c8074ea0a9073e
    on_success: always
    on_failure: always
    on_start: never
